// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxkht8cqNvjJ3UtySXuqAkfuj92k73mV0',
    appId: '1:73267340796:web:90e8f5f0212364b838fe79',
    messagingSenderId: '73267340796',
    projectId: 'hae-free-7c13f',
    authDomain: 'hae-free-7c13f.firebaseapp.com',
    databaseURL: 'https://hae-free-7c13f-default-rtdb.firebaseio.com',
    storageBucket: 'hae-free-7c13f.firebasestorage.app',
    measurementId: 'G-F39GE0GFM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARfJxRyQ0GJlYsCpHm2SUMAa7SCapmEPk',
    appId: '1:73267340796:android:81470d8bb26df10738fe79',
    messagingSenderId: '73267340796',
    projectId: 'hae-free-7c13f',
    databaseURL: 'https://hae-free-7c13f-default-rtdb.firebaseio.com',
    storageBucket: 'hae-free-7c13f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfdMY5vx6TZpnSEjDsZi3VLwWGT-x_h1c',
    appId: '1:73267340796:ios:fd11b0592d0f902238fe79',
    messagingSenderId: '73267340796',
    projectId: 'hae-free-7c13f',
    databaseURL: 'https://hae-free-7c13f-default-rtdb.firebaseio.com',
    storageBucket: 'hae-free-7c13f.firebasestorage.app',
    iosClientId: '73267340796-3jaoipqikf1fgen9nna1kg571g4mp1sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.hassleFree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfdMY5vx6TZpnSEjDsZi3VLwWGT-x_h1c',
    appId: '1:73267340796:ios:fd11b0592d0f902238fe79',
    messagingSenderId: '73267340796',
    projectId: 'hae-free-7c13f',
    databaseURL: 'https://hae-free-7c13f-default-rtdb.firebaseio.com',
    storageBucket: 'hae-free-7c13f.firebasestorage.app',
    iosClientId: '73267340796-3jaoipqikf1fgen9nna1kg571g4mp1sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.hassleFree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxkht8cqNvjJ3UtySXuqAkfuj92k73mV0',
    appId: '1:73267340796:web:462eba9e323a242538fe79',
    messagingSenderId: '73267340796',
    projectId: 'hae-free-7c13f',
    authDomain: 'hae-free-7c13f.firebaseapp.com',
    databaseURL: 'https://hae-free-7c13f-default-rtdb.firebaseio.com',
    storageBucket: 'hae-free-7c13f.firebasestorage.app',
    measurementId: 'G-5959Q7DTFM',
  );

}